Cleanup
stefanpenner/capture-exit pull request #1
Opened 2016-11-10 09:12 UTC by Turbo87

@stefanpenner this should probably be reviewed on a commit-by-commit basis. the last two commits in particular are things I'm not 100% sure about, but in case I understood the code correctly they should work fine.

2016-11-10 15:59 UTC, stefanpenner commented on test.js
> -      process.exit = originalExit;
I think we should keep this one. I think we should restore using abstractions not implemented in this library. As if this library breaks, our tests will break for unrelated reasons

2016-11-10 16:08 UTC, stefanpenner requested changes

2016-11-10 16:08 UTC, stefanpenner commented on index.js
> +        exit.call(process, 1);
apparently then, this code-path isn't tested

2016-11-10 16:11 UTC, Turbo87 commented on test.js
> -      process.exit = originalExit;
as mentioned in the commit message: the outer `afterEach()` block is doing the same thing already. I don't see a reason to reset this twice.

2016-11-10 16:11 UTC, Turbo87 commented on index.js
> +        exit.call(process, 1);
yes, that test appears to be missing

2016-11-11 18:25 UTC, Turbo87 commented
@stefanpenner do you need me to do any changes here? The test was already missing before the PR so we can add that in a separate PR afterwards. Feel free to just cherry pick the good commits for now if you disagree with parts of this PR.

2016-11-11 18:59 UTC, stefanpenner commented
@Turbo87 opened an issue: https://github.com/stefanpenner/capture-exit/issues/3

2016-11-11 18:59 UTC, merged