make process injectable
stefanpenner/capture-exit pull request #23
Opened 2017-07-29 11:34 UTC by ro0gr

this should simplify testing for the `capture-exit` consumers.
see: https://github.com/ember-cli/ember-cli/pull/7229/files#diff-aa94f362c4d6ae97d4d491b3a8cc4887R94

I think it can be better to make `process` instance a required argument in order to be in line with `will-interrupt-process` interface. @stefanpenner @hjdivad any objections?

- [ ] needs tests

2017-07-29 19:56 UTC, stefanpenner requested changes

2017-07-29 19:56 UTC, stefanpenner commented on index.js
> +  _process = p || process;
lets not have module global state, lets just always pass in process.

2017-07-29 21:04 UTC, ro0gr commented
Now `process` is a required argument

```
captureExit(EventEmitter process)
```

2017-07-29 21:12 UTC, stefanpenner requested changes
one nit-pick, then this LGTM

2017-07-29 21:12 UTC, stefanpenner commented on index.js
> +    throw new Error('attempt to capture a bad process instance');
`TypeError`

2017-07-29 21:37 UTC, ro0gr commented on index.js
> +const EventEmitter = require('events');
I wonder how do node@0.12 tests pass

2017-07-29 21:49 UTC, rwjblue commented on index.js
> +const EventEmitter = require('events');
Node 0.12 supports `const`, but only within `'use strict';` mode. http://node.green/#ES2015-bindings-const-basic-support

2017-07-29 21:57 UTC, rwjblue commented
If we are changing to require an argument to be passed in, this will end up needing to be a major version bump (seems totally fine to me). If this is going to be a major version bump, we should drop Node 0.12.

2017-07-29 21:58 UTC, ro0gr commented on index.js
> +const EventEmitter = require('events');
@rwjblue I've added `'use strict';` and 0.12 started to fail. 
What's should we do next? revert `use strict` or update test matrix?

2017-07-29 22:00 UTC, rwjblue commented on index.js
> +const EventEmitter = require('events');
IMHO, update test matrix and drop Node 0.12 (see https://github.com/ember-cli/capture-exit/pull/23#issuecomment-318862262).

2017-07-29 22:01 UTC, ro0gr commented
should i rename pr in some special way?

2017-07-29 22:03 UTC, ro0gr commented
Also I've noticed the last build on appveyor has been started 8 months. Can we restore it?

I have on consistent failure on my pc

2017-07-29 22:09 UTC, stefanpenner commented on index.js
> +  _process = process;
why do we need this?

2017-07-29 22:23 UTC, ro0gr commented on index.js
> +  _process = process;
There are at least two places where we need reference to `_process`:
 - at least for `onBeforeExit` [cleanup](https://github.com/ro0gr/capture-exit/blob/9ed93186b7a66e9a133d48cc68bcfad9d05c6631/index.js#L138) (added in last commit)
 - [`exit` proxy](https://github.com/ro0gr/capture-exit/blob/9ed93186b7a66e9a133d48cc68bcfad9d05c6631/index.js#L142)

2017-07-30 15:34 UTC, stefanpenner commented on index.js
> +  _process = process;
ah, i didn't see those

2017-07-30 15:35 UTC, stefanpenner commented on index.js
> +  _process = process;
I really don't like us using module state for this, but fixing that will be a refactoring we can add later...

2017-08-01 21:26 UTC, ro0gr commented on index.js
> +  _process = process;
Yes, I also don't like this. Hopefully if [everything goes well](https://github.com/ember-cli/ember-cli/pull/7229#issuecomment-319501032) we can close this pr.

2017-08-07 19:46 UTC, ro0gr commented
Closing because I think we can achieve the same goal with something like [MockCaptureExit](https://github.com/ember-cli/ember-cli/pull/7285)

2017-08-07 19:46 UTC, closed without merging